%YAML:1.0

# 1: realtime, 0: non-realtime
test.RealTime: 1
# Time for visual-inertial initialization
test.VINSInitTime: 15.0

# Modify test.InitVIOTmpPath and bagfile to the correct path
# Path to save tmp files/results
test.InitVIOTmpPath: "/home/myntai/LearnVIORB/temp/mynt/"

## For good initialization (no movement at the beginning for some bag)
test.DiscardTime: 0
#test.DiscardTime: 18

bagfile: "/home/myntai/files_bags/30_500.bag"

#######################################

imutopic: "/mynteye/imu/data_raw"
imagetopic: "/mynteye/left/image_mono"


# Timestamp shift. Timage = Timu + image_delay
Camera.delaytoimu: 0

# acc=acc*9.8, if below is 1
IMU.multiplyG: 0

# camera-imu frame transformation, Pi = Tic * Pc
Camera.Tbc:
 [0.99996652, 0.00430873, 0.00695718, -0.04777362,
  0.00434878 , -0.99997401, -0.00575128, -0.00223731,
  0.00693222, 0.00578135, -0.99995926, -0.02160071,
  0.0, 0.0, 0.0, 1.0]

# Local Window size
LocalMapping.LocalWindowSize: 20

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 700.187943 
Camera.fy: 699.855394
Camera.cx: 641.861436
Camera.cy: 367.767547

Camera.k1: -0.325639
Camera.k2: 0.119911
Camera.p1: 0.000158
Camera.p2: 0.000137


# Camera frames per second 
Camera.fps: 20.0

# IR projector baseline times fx (aprox.)
Camera.bf: 77.6

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40 

# Deptmap values factor
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid 
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast   
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

